# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Misti and Blair
email: liffeyhouse@gmail.com
tagline: 'Our Life between a Rock and a Weird Place'
description: Our Life in between a Rock and a Weird Place
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

permalink: pretty

# social
social:
  - title: twitter
    url: https://twitter.com/fbs70
  - title: facebook
    url: https://facebook.com/frederick.shotlow
  - title: instagram
    url: https://instagram.com/blair.shotlow
  - title: github
    url: http://github.com/fbs70

# Build settings
markdown: kramdown

# Include files/folders
include:
  - .nojekyll
# Exclude files/folders
exclude:
  - "Rakefile"
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/fbs70/mistiandblair
